Repository shinhan-7hillguys/7hillguys-front, pull requests merged in 2025-03, with the labels that each got.

#7 6-temp_allowance
  src/pages/peoch/amount/InvestmentSupport.jsx
Labels: enhancement

#14 13 appjsx 작동 되는 버전으로 main pull
  src/App.jsx
  src/pages/peoch/Peoch.jsx
  src/pages/peoch/amount/InvestmentTempAllowance.jsx
Labels: fix

#18 feature/investReview
  src/App.jsx
Labels: fix

#20 Update App.jsx
  src/App.jsx
Labels: fix

#25 6-temp_allowance
  package-lock.json
  package.json
  src/App.jsx
  src/pages/peoch/Peoch.jsx
  src/pages/peoch/amount/InvestmentTempAllowance.jsx
  src/pages/peoch/amount/SetInvestment.jsx
Labels: enhancement

#31 [Fix] package.json에 누락된 dependency 추가
  package-lock.json
  package.json
  src/App.jsx
Labels: bug

#40 [Design] 패키지 추가 및 대시보드 디자인 개선
  package-lock.json
  package.json
  src/App.jsx
  src/components/dashboard/DashboardLayout.jsx
  src/components/dashboard/sidebar.jsx
  src/components/dashboard/topbar.jsx
  src/image/15457.png
  src/pages/admin/Dashboard.jsx
  src/pages/admin/Detail.jsx
  src/pages/admin/searchresult.jsx
  src/styles/globalstyles.jsx
Labels: enhancement

#46 [Design, Style] 데이터 구조에 맞춰 페이지 구조 수정
  src/App.jsx
  src/pages/admin/Detail.jsx
  src/pages/admin/searchresult.jsx
Labels: enhancement

#49 Feature/34 exit
  package-lock.json
  package.json
  src/App.jsx
  src/pages/peoch/Peoch.jsx
  src/pages/peoch/amount/InvestmentExit.jsx
  src/pages/peoch/amount/InvestmentReallyExit.jsx
  src/pages/peoch/amount/InvestmentTempAllowance.jsx
  src/pages/peoch/amount/SetInvestment.jsx
Labels: enhancement

#51 Type: Feat
  src/pages/peoch/amount/SetInvestment.jsx
Labels: fix

#64 Delete .idea directory
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
Labels: fix

#104 Type: Fix
  src/pages/peoch/amount/SetInvestment.jsx
Labels: documentation, fix

#129 [Fix] 기타 스타일 수정 및 수정 요청 사항 개선
  package-lock.json
  src/Main.jsx
  src/components/common/menuData.jsx
  src/components/dashboard/LineChartCard.jsx
  src/components/dashboard/chartcard.jsx
  src/main.css
  src/pages/admin/Detail.jsx
  src/pages/peoch/Peoch.jsx
  src/pages/peoch/Usermain.jsx
Labels: fix
